// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv"
import { defineConfig } from "prisma/config";
dotenv.config() ;


const DATABASE_URL =  process.env.DATABASE_URL ;
if(!DATABASE_URL){
  console.log("yha v nhi mil rhi ");
  
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },

  datasource: {
    url: DATABASE_URL
  },

  
});



